default:
    suites:
        default:
            type: symfony_bundle
            bundle: AppBundle
            contexts:
                - AppBundle\Features\Context\FeatureContext
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            base_url: http://webserver
            browser_name: chrome
            sessions:
                default:
                    selenium2: ~
